//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFLINQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactSystem
    {
        public int IdSystem { get; set; }
        public Nullable<int> IdContact { get; set; }
        public string Description { get; set; }
        public string SystemValue { get; set; }
    
        public virtual NewContact NewContact { get; set; }
    }
}
